name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Install
        run: npm install

      - name: Dist
        run: npm run dist

      - name: Env
        run: env

      - name: Integration Test
        uses: ./
        with:
          file: test/pom.xml
        id: debug

      - name: Env
        run: env

      - name: Output
        run: echo "version=${{ steps.debug.outputs.version }}"
